### ISSUE TITLE
Number of Classes inside .zip file

### ISSUE THREAD

**Issue by cepa995** [leoll2/MedicalCNN#2]
Hi! First of all, I would like to say well done on the project. But, I do have a  question. You are referring to 4-class classification task, but when I loaded data you have provided us a link to I saw 5 classes. My question is, are these classes organized as:
- Normal/Background
- Benign Mass
- Malignant Mass
- Benign Calcification
- Malignant Calcification

Thanks in advance!

**Comment by leoll2** [comment]
Hello Stefan, thanks for appreciating my work.
Yes, the classes are exactly in that order!

**Comment by cepa995** [comment]
Thank you for a quick response! While I have you here, I just have one more question. When you performed binary classification, which of these classes you treated as positive and which as negative? I assume benign and normal/background were negative ones and malignant were positive ones?

**Comment by leoll2** [comment]
The binary classification (Scratch_CNN_2_class) is mass vs calcification.
A variant (Scratch_CNN_ben_mal) is instead benign vs malignant.
The normal/background images are only used in the scripts with the "Baseline_" prefix, and ignored otherwise.
