### ISSUE TITLE
how images were cropped and ROIs extracted in the dataset which you provided?

### ISSUE THREAD

**Issue by LastSemicolon** [leoll2/MedicalCNN#3]
did you extract ROIs from mammography manually? then you classified them !

**Comment by leoll2** [comment]
The abnormality patches were extracted from each DDSM image applying its binary mask, which is also provided in DDSM. The resulting ROI was then rescaled to 150x150. I didn't classify them manually, I am not a radiologist; actually, the CBIS dataset was classified by medical doctors. Find more details [here](https://wiki.cancerimagingarchive.net/display/Public/CBIS-DDSM).
